### PR TITLE
🐞 Bugfix: Incorrect Normal score computation

### PR DESCRIPTION
**Pull request by ashwinvaidya17**
# What does this PR do?

 Addresses: CVS-129988

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Review by Wovchena — APPROVED** [review]

**Comment by ashwinvaidya17** [comment]
I am not sure why is the code quality failing. I merged master to this branch. And now I pulled the branch locally and black passes 
image

**Comment by sovrasov** [comment]
> I am not sure why is the code quality failing. I merged master to this branch. And now I pulled the branch locally and black passes image

The problem is that on CI black version is unconstrained. I checked out you PR, and run black==23.11.0, it shows no errors. When I run black==24.1.1, I see 11 errors.
Could you fix black version to the latest 23.x in `model_api/.github/workflows/test_precommit.yml`? I think this can help.

**Comment by chuneuny-emily** [comment]
When will you release model_api 0.1.9 for this fix?

**Comment by sovrasov** [comment]
> When will you release model_api 0.1.9 for this fix?

I'll release 0.1.9 today

**Pull request merged**
